.TH HCXPCAPTOOL "1"

.SH NAME
hcxpcaptool - convert pcapng, pcap, cap files

.SH SYNOPSIS
.B  hcxpcaptool <options>

.SH DESCRIPTION
.BI hcxpcaptool
is a tool to convert pcapng, pcap, cap files to other hashformats accepted by hashcat and John the Ripper

.SH AUTHOR
This manual page was written by Mike (ZeroBeat).
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so. License MIT

.SH OPTIONS
.TP
.B Common options:
.TP
.I -o <file>
output hccapx file (hashcat -m 2500/2501)
.TP
.I -O <file>
output raw hccapx file (hashcat -m 2500/2501)
.TP
.I -z <file>
output PMKID file (hashcat hashmode -m 16800)
.TP
.I -j <file>
output john WPAPSK-PMK file (john wpapsk-opencl)
.TP
.I -J <file>
output raw john WPAPSK-PMK file (john wpapsk-opencl)
.TP
.I -E <file>
output wordlist (autohex enabled) to use as input wordlist for cracker
.TP
.I -X <file>
output client probelist
.TP
.I -I <file>
output unsorted identity list
.TP
.I -U <file>
output unsorted username list
.TP
.I -M <file>
output unsorted IMSI number list
.TP
.I -P <file>
output possible WPA/WPA2 plainmasterkey list
.TP
.I -T <file>
output management traffic information list
.I -g <file>
output GPS file
.TP
.I -V
verbose (but slow) status output
.TP
.B Other options:
.TP
.I --time-error-corrections=<digit>
maximum allowed time gap (default: 600s)
.TP
.I --nonce-error-corrections=<digit>
maximum allowed nonce gap (default: 8)
.TP
.I --netntlm-out=<file>
output netNTLMv1 file (hashcat -m 5500, john netntlm)
.TP
.I --md5-out=<file>
output MD5 challenge file (hashcat -m 4800)
.TP
.I --md5-john-out=<file>
output MD5 challenge file (john chap)
.TP
.I --tacacsplus-out=<file>
output TACACS+ authentication file (hashcat -m 16100, john tacacs-plus)
.TP
.I --eapol-out=<file>
output EAPOL packets in hex
.TP
.I --network-out=<file>
output network information
.TP
.I --hexdump-out=<file>
output dump raw packets in hex
.TP
.I --hccap-out=<file>
output old hccap file (hashcat -m 2500)
.TP
.I --hccap-raw-out=<file>
output raw old hccap file (hashcat -m 2500)
.TP
.I -h or --help
show help screen
.TP
.I -v or --version
show version
.TP
