.TH WLANCAP2WPASEC "1"

.SH NAME
wlancap2wpasec - upload pcapng, pcap and cap files to online sites

.SH SYNOPSIS
.B  wlancap2wpasec <options>

.SH DESCRIPTION
.BI wlancap2wpasec
is a tool to upload pcapng, pcap and cap files ton online sites, to study and improve security of WPA protected WiFi networks

.SH AUTHOR
This manual page was written by Mike (ZeroBeat).
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so. License MIT

.SH OPTIONS
.TP
.B Common options:
.TP
.I -t <seconds>
set connection timeout
.TP
.B Other options:
.TP
.I -k <key>
send user key
.TP
.I -u <url>
set user defined URL
.TP
.I -e <email address>
set email address, if requiered
.TP
.I -R
remove cap if upload was successful
.TP
.I -h
show help screen
.TP
.I -v
show version
.TP
