INSTALLDIRS	= /usr/local/bin

CC	= gcc
CFLAGS	= -O3 -Wall -Wextra

all: build

build:
	$(CC) $(CFLAGS) -o wlandump wlandump.c -lpcap
	$(CC) $(CFLAGS) $(CFLAGS1) -o wlanscan wlanscan.c -lpcap


install: build
	install -D -m 0755 wlandump $(INSTALLDIRS)/wlandump
	install -D -m 0755 wlanscan $(INSTALLDIR)/wlanscan

	rm -f wlandump
	rm -f wlanscan
	rm -f *.o *~

clean:
	rm -f wlandump
	rm -f wlanscan
	rm -f *.o *~

uninstall:
	rm -f $(INSTALLDIRS)/wlandump
	rm -f $(INSTALLDIR)/wlanscan
