#!/bin/bash

cd /home
export WLANDEV=`ls -1 /sys/class/net | grep ^wl`
if [[ ! -z $WLANDEV ]]
then
	ARCHIVNAME=`date +'%Y%m%d%H%M'`
	ip link set $WLANDEV down
	iw dev $WLANDEV set type monitor
	ip link set $WLANDEV up
	wlandump-ng -i $WLANDEV -o $ARCHIVNAME.cap -c 1 -t 3600 -d 10000 -D 100 -s 0
#	wlandump-ng -i $WLANDEV -o $ARCHIVNAME.cap -c 1 -t 4 -d 25 -D 2 -r -s 0
fi
pioff &
systemctl start dhcpcd@eth0.service
