#!/bin/bash

cd /home
export WLANDEV=`ls -1 /sys/class/net | grep ^wl`
if [[ ! -z $WLANDEV ]]
then
	ARCHIVNAME=`date +'%Y%m%d%H%M'`
	ip link set $WLANDEV down
	iw dev $WLANDEV set type monitor
	ip link set $WLANDEV up
	wlandump-ng -i $WLANDEV -o $ARCHIVNAME.cap -c 1 -t 4 -D -d -E 2 -R -U -B 
#	wlandump-ng -i $WLANDEV -o $ARCHIVNAME.cap -c 1 -t 120 -R -B 
fi
pioff &
systemctl start dhcpcd@eth0.service
